Speed_Sport_Souvenirs/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from base import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tmp/', views.tmp, name="tmp"),
    path('', views.home_page, name="Home"),
    path('product/<int:product_id>', views.product_page, name="Product"),
    path('add_product/', views.add_product_page, name="Add_Product"),
    path('edit_product/<int:product_id>', views.edit_product_page, name="Edit_Product"),
    path('confirm_delete/<int:product_id>', views.confirm_delete_page, name="Confirm_Delete"),
    path('delete_product/<int:product_id>', views.delete_product_page, name="Delete_Product"),
    path('products/', views.search_products, name="Products"),
    path('login/', views.login_page, name="Login"),
    path('logout/', views.logout_method, name="Logout"),
    path('register/', views.register_page, name="Register"),
    path('cart/', views.cart_page, name="Cart"),
    path('profile/<int:user_id>', views.profile_page, name="Profile"),
    path('edit_profile/', views.edit_profile_page, name="Edit_Profile"),
    path('add_to_cart/<int:product_id>/', views.add_to_cart, name='Add_To_Cart'),
    path('cart/remove/<int:item_id>', views.remove_from_cart, name="Remove_From_Cart"),
    path('cart/increment/<int:item_id>/', views.increment_quantity, name='Increment'),
    path('cart/decrement/<int:item_id>/', views.decrement_quantity, name='Decrement'),
    path('cart/payment/', views.payment, name="Payment"),
    path('cart/payment/successful', views.payment_success_page, name="Payment_Success"),
    path('cart/', views.cart_page, name="Cart"),
    path('legal/', views.legal_info_page, name="Legal"),
    path('about/', views.about_page, name="About")
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

base/models.py
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator
from django.db import models


# Create your models here.
class UserInfo(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    profile_image = models.ImageField(upload_to='profile_images/', blank=True, null=True)
    bio = models.TextField(max_length=250, null=True, blank=True)

    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name = "User info"
        verbose_name_plural = "Users info"


class RacingSeries(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Racing Series"
        verbose_name_plural = "Racing Series"


class Team(models.Model):
    name = models.CharField(max_length=100, null=True, blank=True)
    racing_series = models.ForeignKey(RacingSeries, null=True, blank=True, on_delete=models.CASCADE)

    class Meta:
        ordering = ['racing_series', 'name']

    def __str__(self):
        return self.name


class Category(models.Model):
    name = models.CharField(max_length=50, null=True, blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Category"
        verbose_name_plural = "Categories"


class Product(models.Model):
    name = models.CharField(max_length=50)
    price = models.PositiveIntegerField()
    description = models.TextField(max_length=500)
    seller = models.ForeignKey(UserInfo, on_delete=models.CASCADE)
    team = models.ForeignKey(Team, on_delete=models.CASCADE, blank=True, null=True, related_name='products')
    racing_series = models.ForeignKey(RacingSeries, on_delete=models.CASCADE, blank=True, null=True, related_name='products_by_team')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, blank=True, null=True, related_name='products')
    stock = models.PositiveIntegerField(default=1)

    def __str__(self):
        return self.name


class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='product_images/')


class CartItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return self.product.name

    def subtotal(self):
        return self.product.price * self.quantity


class Cart(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    items = models.ManyToManyField(CartItem)

    def calculate_total(self):
        return sum(item.subtotal() for item in self.items.all())

base/forms.py
from django import forms
from .models import *


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'


class UserRegisterForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:

        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password']

    def __init__(self, *args, **kwargs):
        super(UserRegisterForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({'placeholder': 'Username'})
        self.fields['username'].help_text = ''
        self.fields['first_name'].help_text = ''
        self.fields['first_name'].widget.attrs.update({'placeholder': 'Name'})
        self.fields['last_name'].widget.attrs.update({'placeholder': 'Surname'})
        self.fields['email'].widget.attrs.update({'placeholder': 'Email'})
        self.fields['email'].widget.attrs.update({'autocomplete': 'off'})
        self.fields['password'].widget = forms.PasswordInput()
        self.fields['password'].widget.attrs.update({'placeholder': 'Password'})
        self.fields['password'].widget.attrs.update({'autocomplete': 'new-password'})
        for field in self.visible_fields():
            field.label = ''
            field.field.widget.attrs["class"] = "form-control mt-2"

base/views.py
import os

from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db.models import Q
from django.contrib.auth import *
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth import authenticate, login
from .models import *
from .forms import *


# Create your views here.
def home_page(request):
    random_products = list(Product.objects.all().order_by('?')[:5])
    context = {
        'random_products': random_products,
    }
    return render(request, 'home.html', context)


def product_page(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    images = ProductImage.objects.filter(product=product)
    random_products = list(Product.objects.all().order_by('?')[:5])
    in_cart = False
    enable_add_to_cart = False
    if request.user.is_authenticated:
        cart_item = CartItem.objects.filter(cart__user=request.user, product=product).first()
        if cart_item:
            in_cart = True
            if cart_item.quantity == product.stock:
                enable_add_to_cart = False
            else:
                enable_add_to_cart = True
        else:
            enable_add_to_cart = True
    is_owner = (request.user.id == product.seller.user.id)
    context = {
        'product': product,
        'images': images,
        'in_cart': in_cart,
        'enable_add_to_cart': enable_add_to_cart,
        'random_products': random_products,
        'is_owner': is_owner
    }
    return render(request, 'product.html', context)


@login_required
def add_product_page(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        price = request.POST.get('price')
        stock = request.POST.get('stock')
        description = request.POST.get('description')
        category_id = request.POST.get('category')
        category = Category.objects.get(id=category_id)
        racing_series_id = request.POST.get('racing_series')
        racing_series = RacingSeries.objects.get(id=racing_series_id)
        team_id = request.POST.get('team')
        team = Team.objects.get(id=team_id)
        seller = request.user
        user_seller = UserInfo.objects.get(user=seller)

        product = Product(name=name, price=price, description=description, seller=user_seller, team=team, category=category,
                          racing_series=racing_series, stock=stock)
        product.save()

        images = request.FILES.getlist('images')
        for image in images:
            ProductImage.objects.create(product=product, image=image)

        return redirect('Product', product_id=product.id)
    else:
        racing_series = sorted(RacingSeries.objects.all(), key=lambda x: x.name.lower())
        teams = sorted(Team.objects.all(), key=lambda x: x.name.lower())
        categories = sorted(Category.objects.all(), key=lambda x: x.name.lower())

    context = {
        'teams': teams,
        'racing_series': racing_series,
        'categories': categories
    }
    return render(request, 'add_product.html', context)


@login_required
def edit_product_page(request, product_id):
    user = request.user
    user_info = UserInfo.objects.get(user=user)
    product = get_object_or_404(Product, id=product_id)
    if user_info == product.seller or user.is_superuser:
        teams = sorted(Team.objects.all(), key=lambda x: x.name.lower())
        racing_series = sorted(RacingSeries.objects.all(), key=lambda x: x.name.lower())
        categories = sorted(Category.objects.all(), key=lambda x: x.name.lower())

        if request.method == 'POST':
            product.name = request.POST.get('name')
            product.price = request.POST.get('price')
            product.description = request.POST.get('description')
            product.team_id = request.POST.get('team')
            product.racing_series_id = request.POST.get('racing_series')
            product.category_id = request.POST.get('category')
            product.stock = request.POST.get('stock')

            images = request.FILES.getlist('images')
            product_image_objects = []
            for image in images:
                product_image = ProductImage(product=product, image=image)
                product_image.save()
                product_image_objects.append(product_image)

            product.save()

            delete_image_ids = request.POST.getlist('delete_images')
            ProductImage.objects.filter(id__in=delete_image_ids).delete()

            return redirect('Product', product_id=product.id)
    else:
        return redirect('Home')

    context = {
        'product': product,
        'teams': teams,
        'racing_series': racing_series,
        'categories': categories
    }
    return render(request, 'edit_product.html', context)


@login_required
def confirm_delete_page(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    images = ProductImage.objects.filter(product=product)
    user = request.user
    user_info = UserInfo.objects.get(user=user)
    if user_info == product.seller or request.user.is_superuser:
        return render(request, 'confirm_delete.html', {'product': product, 'images': images})
    else:
        return redirect('Home')


@login_required
def delete_product_page(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    user = request.user
    user_info = UserInfo.objects.get(user=user)
    if user_info == product.seller or request.user.is_superuser:
        for product_image in product.productimage_set.all():
            image_path = product_image.image.path
            os.remove(image_path)
        product.delete()
        return redirect('Products')
    else:
        return redirect('Home')


def search_products(request):
    query = request.GET.get('query')
    page_number = request.GET.get('page')
    team_id = request.GET.get('team')
    category_id = request.GET.get('category')
    racing_series_id = request.GET.get('racing_series')

    products = Product.objects.all()

    if query:
        products = products.filter(Q(name__icontains=query) | Q(description__icontains=query) | Q(team__name__icontains=query) | Q(racing_series__name__icontains=query))

    if team_id:
        products = products.filter(team__id=team_id)

    if category_id:
        products = products.filter(category__id=category_id)

    if racing_series_id:
        products = products.filter(racing_series__id=racing_series_id)

    teams = sorted(Team.objects.all(), key=lambda x: x.name.lower())
    racing_series = sorted(RacingSeries.objects.all(), key=lambda x: x.name.lower())
    categories = sorted(Category.objects.all(), key=lambda x: x.name.lower())

    products = products.order_by('-id')

    products_per_page = request.GET.get('per_page', 10)
    paginator = Paginator(products, products_per_page)
    page_obj = paginator.get_page(page_number)
    random_products = list(Product.objects.all().order_by('?')[:5])

    context = {
        'query': query,
        'products': page_obj,
        'products_per_page': products_per_page,
        'teams': teams,
        'racing_series': racing_series,
        'categories': categories,
        'random_products': random_products,
    }

    return render(request, 'products.html', context)


def login_page(request):
    if not request.user.is_authenticated:
        if request.method == 'POST':
            username = request.POST['usernameInput']
            password = request.POST['passwordInput']
            remember_me = request.POST.get('remember_me') == 'on'
            user = authenticate(request, username=username, password=password)

            if user is not None:
                login(request, user)
                if remember_me:
                    request.session.set_expiry(settings.SESSION_COOKIE_AGE)
                next_url = request.POST.get('next', 'Home')
                return redirect(next_url)
            else:
                error_message = 'Invalid username or password'
                return render(request, 'login.html', {'error_message': error_message})

        return render(request, 'login.html')
    return redirect('Home')


def logout_method(request):
    logout(request)
    next_url = request.POST.get('next', 'Home')
    return redirect(next_url)


def register_page(request):
    if not request.user.is_authenticated:
        if request.method == 'POST':
            form = UserRegisterForm(request.POST)
            if form.is_valid():
                first_name = form.cleaned_data['first_name']
                last_name = form.cleaned_data['last_name']
                email = form.cleaned_data['email']
                password = form.cleaned_data['password']
                username = form.cleaned_data['username']
                user = User.objects.create_user(username=username, first_name=first_name, last_name=last_name, email=email,
                                                password=password)
                user_info = UserInfo.objects.create(user=user)
                return redirect('/')
        else:
            form = UserRegisterForm()
        return render(request, 'register.html', {'form': form})
    return redirect('Home')


def profile_page(request, user_id):
    user = User.objects.get(id=user_id)
    user_info = UserInfo.objects.get(user=user)
    products = Product.objects.filter(seller=user_info)
    products = products.order_by('-id')
    page_number = request.GET.get('page')
    products_per_page = request.GET.get('per_page', 10)
    paginator = Paginator(products, products_per_page)
    page_obj = paginator.get_page(page_number)

    is_owner = (request.user.id == user.id)

    context = {
        'user_info': user_info,
        'is_owner': is_owner,
        'products': page_obj,
        'products_per_page': products_per_page,
    }
    return render(request, 'profile.html', context)


@login_required
def edit_profile_page(request):

base/templates/about.html
{% extends 'base.html' %}

{% block content %}
<div class="container my-5 text-align-center">
    <h2>About Us - Speed & Sport Souvenirs</h2>
    <p>Welcome to Speed & Sport Souvenirs, the number one online marketplace
        for passionate fans of various racing series in the world of
        motorsports. We are dedicated to providing a wide range of souvenirs
        and memorabilia that allow you to showcase your love and
        support for your favorite motorsport.
    </p>

    <p>At Speed & Sport Souvenirs, we understand the thrill and excitement
        that motorsports bring to fans worldwide. Whether you're a fan of
        Formula 1, NASCAR, MotoGP, WRC, or any other racing series, we
        offer a collection of high-quality merchandise that celebrates the
        spirit and adrenaline of these iconic sports.</p>

    <p>Our mission is to be the go-to destination for racing enthusiasts
        looking for authentic and unique souvenirs and memorabilia. We strive
        to create a seamless online shopping experience where you can easily
        discover and acquire the perfect items to display your dedication
        and passion for your favorite racing series, team or driver.</p>

    <p>We are not just a marketplace; we are enthusiasts ourselves. Our team
        consists of passionate motorsports fans who understand the value of
        authentic memorabilia and the joy it brings to fellow fans. We share
        your excitement and strive to bring you the very best selection of
        items that resonate with your love for racing.</p>

    <p>Thank you for choosing Speed & Sport Souvenirs as your premier online
        destination for racing souvenirs and memorabilia. We look forward to
        serving you and helping you find the perfect items to express your
        passion for the thrilling world of motorsports.</p>

    <p class="fw-bold">Start exploring our collection today and let your love for speed and sport shine!</p>

    <p>The Speed & Sport Souvenirs Team</p><msg hidden>More like the one guy working on this lule"</msg>
</div>
{% endblock %}

base/templates/add_product.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
  <h1>Add Product</h1>
  <form method="post" enctype="multipart/form-data" action="{% url 'Add_Product' %}">
    {% csrf_token %}
    <div class="mb-3">
      <label for="id_name" class="form-label">Name</label>
      <input type="text" class="form-control" id="id_name" name="name" required>
    </div>
    <div class="mb-3">
      <label for="id_price" class="form-label">Price</label>
      <input type="number" class="form-control" id="id_price" name="price" required>
    </div>
    <div class="mb-3">
      <label for="id_description" class="form-label">Description</label>
      <textarea class="form-control" id="id_description" name="description" rows="3" required></textarea>
    </div>
    <div class="mb-3">
      <label for="id_images" class="form-label">Images</label>
      <input type="file" class="form-control" id="id_images" name="images" accept="image/*" multiple required>
      <small class="form-text text-muted">You can upload multiple images by selecting multiple files.</small>
    </div>
    <div class="mb-3">
      <label for="racing_series_select" class="form-label">Racing Series</label>
      <select class="form-select" id="racing_series_select" name="racing_series" required>
        <option value="">Choose a racing series</option>
        {% for series in racing_series %}
        <option value="{{ series.id }}">{{ series.name }}</option>
        {% endfor %}
      </select>
    </div>
    <div class="mb-3">
      <label for="team_select" class="form-label">Team</label>
      <select name="team" id="team_select" class="form-select" required disabled>
          <option value="" selected disabled>Select Team</option>
          {% for team in teams %}
              <option value="{{ team.id }}" data-series="{{ team.racing_series_id }}">{{ team.name }}</option>
          {% endfor %}
      </select>
    </div>
    <div class="mb-3">
      <label for="id_category" class="form-label">Category</label>
      <select class="form-select" id="id_category" name="category" required>
        <option value="">Choose a category</option>
        {% for category in categories %}
        <option value="{{ category.id }}">{{ category.name }}</option>
        {% endfor %}
      </select>
    </div>
    <div class="mb-3">
      <label for="id_stock" class="form-label">Stock</label>
      <input type="number" class="form-control" id="id_stock" name="stock" value="1" required>
    </div>
    <button type="submit" class="btn btn-primary">Add Product</button>
  </form>
</div>

<script>
const racingSeriesSelect = document.getElementById('racing_series_select');
const teamSelect = document.getElementById('team_select');
const teams = Array.from(teamSelect.options);

racingSeriesSelect.addEventListener('change', (event) => {
    const selectedSeriesId = event.target.value;
    teamSelect.innerHTML = '';
    teamSelect.disabled = true;

    teams.forEach((team) => {
        const teamSeriesId = team.getAttribute('data-series');

        if (teamSeriesId === selectedSeriesId || teamSeriesId === '') {
            teamSelect.appendChild(team.cloneNode(true));
        }
    });

    teamSelect.disabled = false;
});
</script>
{% endblock %}

base/templates/add_to_cart.html
{% extends 'base.html' %}

{% block content %}

{% endblock %}

base/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <title>Speed & Sport Souvenirs</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
</head>
<body>
    <header class="p-3 text-bg-danger">
      <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
          <a href="{% url 'Home' %}" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
            <img src="{{ MEDIA_URL }}other_media/checkered_flag_logo.png" alt="Image" class="bi me-2" width="40" height="32" role="img"/>
          </a>

          <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
            <li><a href="{% url 'Home' %}" class="nav-link px-2 text-white">Home</a></li>
            <li><a href="{% url 'Products' %}" class="nav-link px-2 text-white">Products</a></li>
            <li><a href="{% url 'About' %}" class="nav-link px-2 text-white">About</a></li>


            {% if user.is_authenticated %}
              <li><a href="{% url 'Add_Product' %}" class="nav-link px-2 text-white">Sell Something</a></li>
              <li><a class="nav-link px-2 text-white">Welcome, {{ user.username }}</a></li>
              <li><a href="{% url 'Profile' user.id %}" class="nav-link px-2 text-white">My Profile</a></li>
            {% endif %}
          </ul>

          {% if user.is_authenticated %}
            <a href="{% url 'Cart' %}" class="btn btn-light mx-3">Your cart</a>
          {% endif %}
          <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3 d-flex align-items-center" role="search" action="{% url 'Products' %}" method="GET">
            <input type="text" name="query" class="form-control form-control-dark me-2" placeholder="Quick Search" aria-label="Search">
            <button type="submit" class="btn btn-primary">Search</button>
          </form>

          <div class="text-end">
            {% if user.is_authenticated %}
              <button type="button" class="btn btn-outline-light" onclick="window.location.href={% url 'Logout' %}">Log out</button>
            {% else %}
              <button type="button" class="btn btn-outline-light me-2" onclick="window.location.href={% url 'Login' %}">Login</button>
              <button type="button" class="btn btn-primary" onclick="window.location.href={% url 'Register' %}">Register</button>
            {% endif %}
          </div>
        </div>
      </div>
    </header>

    {% block content %}

    {% endblock %}
    <hr>
    <div class="container mt-4 mb-0">
      <footer class="py-5">
      <div class="row">
        <div class="col-6 col-md-2 mb-4">
          <h5>Section</h5>
          <ul class="nav flex-column">
            <li class="nav-item mb-2"><a href="{% url 'Home' %}" class="nav-link p-0 text-body-secondary">Home</a></li>
            <li class="nav-item mb-2"><a href="{% url 'Products' %}" class="nav-link p-0 text-body-secondary">Products</a></li>
            <li class="nav-item mb-2"><a href="{% url 'About' %}" class="nav-link p-0 text-body-secondary">About</a></li>
            <li class="nav-item mb-2"><a href="{% url 'Legal' %}" class="nav-link p-0 text-body-secondary">Disclaimer</a></li>
          </ul>
        </div>

      <div class="d-flex flex-column flex-sm-row justify-content-between py-4 my-4 border-top">
        <p>© (or lack thereof) 2024 Борис Тодоров, 191096. No rights reserved.</p>
        <ul class="list-unstyled d-flex">
          <li class="ms-3 text-dark"><a class="link-body-emphasis" href="{% url 'tmp' %}"><svg class="bi" width="24" height="24"></svg></a></li>
        </ul>
      </div>
      </footer>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    {% block script %}
    {% endblock %}
</body>
</html>

base/templates/confirm_delete.html
{% extends 'base.html' %}
{% load humanize %}

{% block content %}
<div class="container my-4">
    <div class="row">
        <div class="col-md-6">
            <div id="carousel" class="carousel slide" data-bs-ride="carousel">
                <ol class="carousel-indicators">
                    {% for image in images %}
                    <ul data-bs-target="#carousel" data-bs-slide-to="{{ forloop.counter0 }}" {% if forloop.first %}class="active"{% endif %}></ul>
                    {% endfor %}
                </ol>
                <div class="carousel-inner">
                    {% for image in images %}
                    <div class="carousel-item {% if forloop.first %}active{% endif %}">
                        <img class="img-fluid" src="{{ image.image.url }}" alt="Product Image">
                    </div>
                    {% endfor %}
                </div>
                <a class="carousel-control-prev" href="#carousel" role="button" data-bs-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carousel" role="button" data-bs-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Next</span>
                </a>
            </div>
        </div>
        <div class="col-md-6">
            <h1>{{ product.name }}</h1>
            <h2>${{ product.price|intcomma }}</h2>
            <h4>{{ product.racing_series }} - {{ product.team }} - {{ product.category }}</h4>
            <p>Available stock: {{ product.stock }}</p>
            <p>{{ product.description }}</p>

            {% if is_owner or user.is_superuser %}
                <a href="{% url 'Edit_Product' product_id=product.id %}" class="btn btn-primary my-2">Edit Product</a>
                <a href="{% url 'Delete_Product' product_id=product.id %}" class="btn btn-warning my-2">Delete Product</a>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

base/templates/edit_product.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h2>Editing Product</h2>
     <form method="post" enctype="multipart/form-data" action="">
        {% csrf_token %}
        <div class="mb-3">
          <label for="id_name" class="form-label">Name</label>
          <input type="text" class="form-control" id="id_name" name="name" value="{{ product.name }}" required>
        </div>
        <div class="mb-3">
          <label for="id_price" class="form-label">Price</label>
          <input type="number" class="form-control" id="id_price" name="price" value="{{ product.price }}" required>
        </div>
        <div class="mb-3">
          <label for="id_description" class="form-label">Description</label>
          <textarea class="form-control" id="id_description" name="description" rows="3" required>{{ product.description }}</textarea>
        </div>
        <div class="mb-3">
          <label for="racing_series_select" class="form-label">Racing Series</label>
          <select class="form-select" id="racing_series_select" name="racing_series" value="{{ product.racing_series }}" required>
            <option value="">{{ product.racing_series }}</option>
            {% for series in racing_series %}
              <option value="{{ series.id }}">{{ series.name }}</option>
            {% endfor %}
          </select>
        </div>
        <div class="mb-3">
          <label for="team_select" class="form-label">Team</label>
          <select name="team" id="team_select" class="form-select" value="{{ product.team }}" required disabled>
              <option value="" selected disabled>Select Team</option>
              {% for team in teams %}
                  <option value="{{ team.id }}" data-series="{{ team.racing_series_id }}">{{ team.name }}</option>
              {% endfor %}
          </select>
        </div>
        <div class="mb-3">
          <label for="id_category" class="form-label">Category</label>
          <select class="form-select" id="id_category" name="category" value="{{ product.category }}" required>
            <option value="">{{ product.category }}</option>
            {% for category in categories %}
            <option value="{{ category.id }}">{{ category.name }}</option>
            {% endfor %}
          </select>
        </div>
        <div class="mb-3">
          <label for="id_stock" class="form-label">Stock</label>
          <input type="number" class="form-control" id="id_stock" name="stock" value="{{ product.stock }}" required>
        </div>
          <div class="mb-3">
          <label for="id_images" class="form-label">Add new images</label>
          <input type="file" class="form-control" id="id_images" name="images" accept="image/*" multiple>
          <small class="form-text text-muted">You can upload multiple images by selecting multiple files.</small>
        </div>
        <div class="mb-3">
            <label for="id_delete_images" class="form-label">Delete images</label>
            {% for image in product.productimage_set.all %}
            <div class="form-check">
                <input class="form-check-input" type="checkbox" name="delete_images" value="{{ image.id }}">
                <img src="{{ image.image.url }}" alt="Product Image" class="img-thumbnail">
            </div>
            {% endfor %}
        </div>
            <button type="submit" class="btn btn-primary">Save Changes</button>
     </form>
</div>
<script>
const racingSeriesSelect = document.getElementById('racing_series_select');
const teamSelect = document.getElementById('team_select');
const teams = Array.from(teamSelect.options);

racingSeriesSelect.addEventListener('change', (event) => {
    const selectedSeriesId = event.target.value;
    teamSelect.innerHTML = '';
    teamSelect.disabled = true;

    teams.forEach((team) => {
        const teamSeriesId = team.getAttribute('data-series');

        if (teamSeriesId === selectedSeriesId || teamSeriesId === '') {
            teamSelect.appendChild(team.cloneNode(true));
        }
    });

    teamSelect.disabled = false;
});
</script>
{% endblock %}